stages:
  - build
  - sonar
  - test
  - allure

build:
  stage: build
  tags:
    - gitlab-org-docker
  script:
    - docker login -u $GITLAB_USER_LOGIN -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE/dev:try" .
    - docker push "$CI_REGISTRY_IMAGE/dev:try"

